#include "i_52.h"
#include "i_12.h"
#include "i_02.h"
#include "i_53.h"
#include "i_25.h"
#include "i_07.h"
#include "i_33.h"
#include <pthread.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>
